service: Lambda # NOTE: update this with your service name

provider:
  name: aws
  runtime: dotnetcore2.1

# you can overwrite defaults here
  stage: dev
  region: ap-northeast-1
  environment:
        TZ: Asia/Tokyo

package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    events:
      - http:
          path: hello
          method: post

    # you can add packaging information here
    package:
      artifact: bin/release/netcoreapp2.1/hello.zip
    #  exclude:
    #    - exclude-me.js
    #    - exclude-me-dir/**
    role: !GetAtt lambdaHelloRole.Arn

resources:
  Resources:
    MeetingRoomBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: meeting-room-bucket
    
    lambdaHelloRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: LambdaHelloRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: lambdaPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - s3:*
                    # - s3:PutObject
                    # - s3:ListBucket
                    # - s3:GetObject
                    # - s3:DeleteObject
                    # - s3:CreateBucket
                  Resource: '*'
                - 
                  Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogGroups
                    - logs:PutSubscriptionFilter
                  Resource: '*'