@startuml

class 予約者
class 予約

rectangle 予約する時に必要な情報 {
    class 予約者ID
    rectangle ここは一緒の情報？ {
        class 会議室
        class "会議時間 ReservedTimeSpan" as ReservedTimeSpan {
            - 開始時間
            - 終了時間
            + 数値時間() 
        }
    }
    ReservedTimeSpan --> 開始時間 : use
    ReservedTimeSpan --> 終了時間 : use
    ReservedTimeSpan --> 日付 : use
    class 予約人数
    class 予約者ID
    note bottom of 予約者ID
    誰が予約したか
    end note 
    note bottom of 予約人数
    今回、これ何人？
    end note
}

note right of ReservedTimeSpan
15分単位
end note
note bottom of ReservedTimeSpan
30日後まで予約できる
end note
note bottom of ReservedTimeSpan
ReservedTimeSpanは10:00-19:00
end note

note bottom of ReservedTimeSpan
同日じゃないと駄目というルールが必要かもしれない
end note

@enduml