@startuml

class 予約者
class 予約

rectangle 予約する時に必要な情報 {
    class 会議室
    class 予約者ID
    class 会議時間
    note bottom of 会議時間
    15分単位
    end note
    class 予約時間 {
        - 会議時間
        - 開始時間
        - 終了時間
        - 日付
    }
    予約時間 --> 会議時間 : use
    予約時間 --> 開始時間 : use
    予約時間 --> 終了時間 : use
    予約時間 --> 日付 : use
    class 予約人数
    class 予約者ID
    note bottom of 予約者ID
    誰が予約したか
    end note 
}

note right of 予約時間
15分単位
end note
note bottom of 予約時間
30日後まで予約できる
end note
note bottom of 予約時間
予約時間は10:00-19:00
end note

@enduml