@startuml
left to right direction

actor 予約者
rectangle  {
    予約者 -- (会議室を予約する)
    予約者 -- (会議室をキャンセルする)
    予約者 -- (会議室の予約時間を変更する)
    予約者 -- (会議室の利用を開始する)
    予約者 -- (会議室の利用を終了する)
}

note bottom of (会議室を予約する)
予約対象の会議室が埋まっていたら、
予約できない
end note
@enduml