on: pull_request

name: Check

jobs:
  build:
    runs-on: ubuntu-16.04    
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      # PRしてきたブランチのソースコードがチェックアウトされる
      - uses: actions/checkout@v2

      # dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'
      
      - run: |
          cd Lambda 
          ./build.sh
