on: pull_request

name: Check

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: ['3.1.100']
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      # PRしてきたブランチのソースコードがチェックアウトされる
      - uses: actions/checkout@v2

      # dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      
      - run: |
          cd Lambda 
          ./build.sh