name: Deploy

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGEON: ${{ secrets.AWS_REGEON }}

jobs:
  build:
    runs-on: ubuntu-16.04    
    name: Dotnet build Check
    steps:
      # PRしてきたブランチのソースコードがチェックアウトされる
      - uses: actions/checkout@v2
        
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Serverless
        run: |
          npm install -g serverless

      # dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'
      - run: |
          cd Lambda 
          ./build.sh
      - name: Deploy
        run: |
          cd Lambda
          sls deploy 

